import unittest

raise unittest.TestCase.failureException("hi")